# Generated by Django 2.1.2 on 2018-10-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sen', models.CharField(max_length=200)),
                ('changed_to_sen', models.CharField(max_length=200)),
            ],
        ),
    ]
