# Generated by Django 2.1.2 on 2018-11-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memegenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memegenerator',
            old_name='changed_to_sen',
            new_name='changed_to_sentence',
        ),
        migrations.RenameField(
            model_name='memegenerator',
            old_name='original_sen',
            new_name='original_sentence',
        ),
    ]
